### ISSUE TITLE
APL symbols are inconsistent

### ISSUE THREAD

**Issue by abrudz** [fabrizioschiavi/pragmatapro#64]
I'd love to use Pragmata Pro for programming in APL, but the inconsistencies bother me. Compare Pragmata Pro to the much more harmonious ([public domain](http://apl385.com/fonts/)) APL385 Unicode:

![Pragmata Pro vs APL385 Unicode](https://user-images.githubusercontent.com/10961427/26904751-704ed77c-4bdb-11e7-8936-7d736787ae90.png)

**Comment by fabrizioschiavi** [comment]
This is a very helpful table! Thank you!
I’ll fix them asap

**Comment by abrudz** [comment]
Here is the raw text. That should make it easier to find the glyphs in question
```
          stars: *⍣⍟
        circles: ⍥○⍟⌽⍉⊖⍜⊙
        slashes: /⌿⍁%
    backslashes: \⍀⍂
        uptacks: ⍊⍎⊥
      downtacks: ⍡⍑⍕⊤
       epsilons: ∉∊⍷
           jots: ∘⍤⍛¤⍝
         commas: ,⍪;⍮
       diamonds: ⋄⌺⍚
           dels: ⍫∇⍢⍒
         stiles: ⍒⍋∥⍭|⍦
         deltas: ∆⍙⍋
      up arrows: ↑⍐⍏
    down arrows: ⍖⍗↓
```

**Comment by fabrizioschiavi** [comment]
@abrudz, it is better now?
![pragmatapro0 826_apl](https://user-images.githubusercontent.com/1576663/29457751-13ebc66a-841c-11e7-9c45-eeee27d117c4.png)

**Comment by Porges** [comment]
I think U+2209 (first 'epsilon') is too big, should be the same size as the U+2208 only with a slash?

IMO the rest look really nice and consistent 👏 🙂

**Comment by abrudz** [comment]
Huge improvement. Is is just me or are `⊖` and `⊙` slightly bigger than the other circles? Would you consider moving the normal star down to the level of `⍣` and `⍟`? I think it would look better in most programming languages, as it is a stand-in for the multiplication sign, `×`. Also, the diamond in `⌺` is a bit too tall, especially since it could be (is?) smaller than `⋄` and `⍚`. But all these are nitpicks. Great job!

**Comment by fabrizioschiavi** [comment]
I’m waiting eagerly your feedback about the improvements in consistency I done in PragmataPro 0.827 version. Please let me know. Thank you!

**Comment by abrudz** [comment]
@fabrizioschiavi I don't have a license. Could you make a screenshot of
```
          stars: *⍣⍟
        circles: ⍥○⍟⌽⍉⊖⍜⊙
        slashes: /⌿⍁%
    backslashes: \⍀⍂
        uptacks: ⍊⍎⊥
      downtacks: ⍡⍑⍕⊤
       epsilons: ∉∊⍷
           jots: ∘⍤⍛¤⍝
         commas: ,⍪;⍮
       diamonds: ⋄⌺⍚
           dels: ⍫∇⍢⍒
         stiles: ⍒⍋∥⍭|⍦
         deltas: ∆⍙⍋
      up arrows: ↑⍐⍏
    down arrows: ⍖⍗↓
```

**Comment by fabrizioschiavi** [comment]
![screen shot 2018-09-09 at 15 39 14](https://user-images.githubusercontent.com/1576663/45265087-8c56a880-b446-11e8-9083-3f20b2da59d3.png)

**Comment by abrudz** [comment]
@fabrizioschiavi This is very good. Only tiny nitpicks:
The `○` in `⍜` seems a bit higher than the other circles.
The `-` in `⍀` seems off-center.
The `⊤` in `⍑` seems to have a longer stem than the other tacks.

**Comment by fabrizioschiavi** [comment]
![PragmataPro 0.828 APL](https://user-images.githubusercontent.com/1576663/62455143-09cd8a80-b776-11e9-97b1-02ed145f1891.png)

**Comment by abrudz** [comment]
Looks very good.

- the stars `⍣` and `⍟` regressed to a pentagram shape
- `⍜`'s circle has slightly less height than all other circles
- the horizontal bar of `⌿` and `⍀` has moved below the centre, which imho looks odd
- I think `⍝` is oversized — it could be scaled down so the circle matches the size of `∘`

Some comparisons are not in the chart. You could add:

- `⌼⊚` to the circles
- comparison of arrows: `←→⍇⍈⍅⍆`
- comparison of diaereses: `¨⍨⍤⍥⍢⍣⍡`
- comparison of shoes: `⊂⊆⊇⊃∪⍦⋔∩⍝`

Btw, APL traditionally uses the circled alphabet, but Unicode doesn't have that, so it was mapped to the circled alphabet. However, in a monospace font (like APL385 Unicode), a circle cannot really fit, so it glyphs were made underscored. Maybe consider doing the same for:

ⒶⒷⒸⒹⒺⒻⒼⒽⒾⒿⓀⓁⓂⓃⓄⓅⓆⓇⓈⓉⓊⓋⓌⓍⓎⓏ  
`ⒶⒷⒸⒹⒺⒻⒼⒽⒾⒿⓀⓁⓂⓃⓄⓅⓆⓇⓈⓉⓊⓋⓌⓍⓎⓏ`  
![image](https://user-images.githubusercontent.com/10961427/62470530-8a01e900-b792-11e9-9a52-84c97ea4e773.png)

**Comment by ab5tract** [comment]
Hi there, just purchased this awesome font! I just wanted to bump this thread to let you know that I for one would love to see some of those finishing touches mentioned by @abrudz in his latest comment in the next version of PragmataPro.

That said, it's well on it's way as a beautiful font to code some APL in! Thanks for your time.

**Comment by ab5tract** [comment]
It is also worth noting that the plus symbol and the left arrow are not vertically aligned. Thus `+←` looks quite strange relative to how they appear in most fonts.

**Comment by fabrizioschiavi** [comment]
These are [PragmataPro](https://fsd.it/shop/fonts/pragmatapro/) APL glyphs since v_0.829

![Screenshot 2021-05-19 at 19 49 16](https://user-images.githubusercontent.com/1576663/118860288-809c2f00-b8db-11eb-9a38-fadea53e0114.png)

All right now?

**Comment by fabrizioschiavi** [comment]
Yes,  `⊥` , `⊤` , `←` and `→` are only double-width in the modularspaces font.

I just fixed all the other issue.
What do you think now?

![Screenshot 2021-05-20 at 17 58 58](https://user-images.githubusercontent.com/1576663/119011587-7e96a680-b995-11eb-8174-9028ccb8562d.png)

**Comment by abrudz** [comment]
Looks perfect to me.

**Comment by Porges** [comment]
@fabrizioschiavi I think `⊥` and `⊤` shouldn’t ever be double-width, I’ve never seen them presented like that before. I love how you’ve done the rest!

**Comment by rabbitgrowth** [comment]
Thank you so much for these improvements. However, I’ve noticed that they’ve only been incorporated into PragmataPro, PragmataPro Liga, and PragmataPro Mono Liga, but not PragmataPro Mono, where several problems remain:

- `⍣` `⍟` still have pentagram shapes inconsistent with `*`. (The `*` is also slightly higher compared to PragmataPro, PragmataPro Liga, and PragmataPro Mono Liga.)
- The circles in `⌽` `⍉` are smaller than the ones in `⍥` `○` `⍟` `⊖` `⍜` `⊙`.
- The stem in `⍑` is still longer than the ones in `⍡` `⍕` `⊤`.
- The `,` in `,` `⍪` `;` `⍮` all have different shapes.

I would appreciate it very much if these could be fixed in an upcoming version. The `⍣` seems particularly problematic, as it’s a common symbol in APL, and the pentagram shape stands out as inconsistent.

**Comment by fabrizioschiavi** [comment]
@rabbitgrowth thanks for this useful comment. I'll fix all these issue soon

**Comment by fabrizioschiavi** [comment]
Fixed! Please re-download the font files from fsd.it
